# Appropriate terminal colors
#set -g default-terminal "xterm-256color"
#set -ga terminal-overrides ",xterm-256color:Tc"

set -g mouse on

# Start tabs at index 1
set -g base-index 1

# Free the original `Ctrl-b` prefix keybinding.
unbind C-b

# set prefix key to ctrl-a
set -g prefix C-a

# Configurações da status bar
set -g status-position bottom  # status bar na parte inferior (padrão)
set -g status on               # habilita a status bar
set -g status-interval 1       # atualiza a cada 1 segundo

# Configurações visuais da status bar
set -g status-justify left
set -g status-style 'bg=black,fg=white'
set -g status-left-length 100
set -g status-right-length 100

# plugins
set -g @plugin 'lucasfcosta/catpuccin-tmux' # tmux theme <3
set -g @plugin 'tmux-plugins/tmux-cpu' # shows cpu status in status bar
set -g @plugin 'tmux-plugins/tmux-battery' # shows battery stats in status bar
set -g @plugin 'tmux-plugins/tmux-online-status' # shows internet status in status bar
set -g @plugin 'tmux-plugins/tmux-pain-control' # better control of panes
set -g @plugin 'tmux-plugins/tmux-resurrect' # persists sessions between shutdowns/restarts
set -g @plugin 'tmux-plugins/tmux-continuum' # continuous save/reload sessions
set -g @plugin 'robhurring/tmux-spotify' # spotify songs

# TPM sempre na última linha
run '~/.tmux/plugins/tpm/tpm'
